apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-notification-service
  template:
    metadata:
      labels:
        app: discord-notification-service
    spec:
      containers:
      - name: discord-notification-service
        image: gcr.io/wondrous-1587456307075/discord-notification-service:VERSION
        ports:
        - containerPort: 5001
        env:
          - name: CORE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: core-api-secret
                key: CORE_API_SECRET
          - name: WONDER_DISCORD_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: wonder-discord-bot-token
                key: WONDER_DISCORD_BOT_TOKEN